import getConfig from "next/config";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [title, setTitle] = useState("");
  const [contents, setContents] = useState("");

  async function fetchPosts() {
    try {
      const response = await fetch("/api/posts");
      if (!response.ok) {
        throw new Error("Failed to fetch posts");
      }
      const posts = await response.json();
      console.log(posts); // 받아온 게시글들을 콘솔에 출력 또는 UI에 표시
    } catch (error) {
      console.error(error);
    }
  }

  async function createPost() {
    try {
      const response = await fetch("/api/posts", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          title,
          contents,
        }),
      });
      if (!response.ok) {
        throw new Error("Failed to create post");
      }
      const newPost = await response.json();
      console.log(newPost); // 새로 생성된 게시글을 콘솔에 출력 또는 UI에 표시
    } catch (error) {
      console.error(error);
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={fetchPosts}>test</button>
        <button onClick={createPost}>만들기</button>
        <input value={title} onChange={(e) => setTitle(e.target.value)} />
        <input value={contents} onChange={(e) => setContents(e.target.value)} />
      </main>
    </>
  );
}
